Use a file to store the segger sn

diff --git a/scripts/gdb_server b/scripts/gdb_server
--- a/scripts/gdb_server
+++ b/scripts/gdb_server
@@ -2,25 +2,27 @@
 # Starts a Segger GDB server
 # $1: 0 = sn0, 1 = sn1
 # $2: Port number, default if not specified
-sn0="260103290"
-sn1="260108510"
+
+# Any subsequent(*) commands which fail will cause the shell script to exit immediately
+set -e
+
+serialfile="$HOME/.scripts/segger_sn.txt"
 
 if [ -z "$1" ]
 then
-	sn=$sn0
+	serialidx=1
 	port=2331
 	swoport=2332
 	telport=2333
 else
+	serialidx=`expr $1 + 1`
 	if [ "$1" == "0" ]
 	then
-		sn=$sn0
 		port=2331
 		swoport=2332
 		telport=2333
 	elif [ "$1" == "1" ]
 	then
-		sn=$sn1
 		port=2341
 		swoport=2342
 		telport=2343
@@ -28,6 +30,12 @@ else
 		echo "Unknown device $1"
 		exit 1
 	fi
+fi
+
+sn=`sed "${serialidx}q;d" $serialfile`
+if [ "$sn" == "" ]; then
+	echo "Cannot find segger serial number"
+	exit
 fi
 
 if [ -n "$2" ]
diff --git a/scripts/segflash b/scripts/segflash
--- a/scripts/segflash
+++ b/scripts/segflash
@@ -1,6 +1,8 @@
 #!/bin/bash
-set -e
 # Any subsequent(*) commands which fail will cause the shell script to exit immediately
+set -e
+
+serialfile="$HOME/.scripts/segger_sn.txt"
 if [ "$#" -ne 2 ]; then
 	echo "Usage: segflash <brm|brx|mch> <0|1>"
 	exit
@@ -15,16 +17,10 @@ else
 	exit
 fi
 
-if [ "$2" == "0" ]; then
-	#sn=26010741
-	sn=260103290
-elif [ "$2" == "1" ]; then
-	#sn=260107676
-	#sn=260110685
-	#sn=260110112
-	sn=260108510
-else
-	echo "Arg2 should be 0 or 1 depending of segger used"
+serialidx=`expr $2 + 1`
+sn=`sed "${serialidx}q;d" $serialfile`
+if [ "$sn" == "" ]; then
+	echo "Cannot find segger serial number"
 	exit
 fi
 
